//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIGA.Pipelines.SitecoreWebservices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [DataContract(Name="Credentials", Namespace="http://sitecore.net/visual/")]
    [Serializable()]
    public partial class Credentials : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [NonSerialized()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [OptionalField()]
        private string CustomDataField;
        
        [OptionalField()]
        private string PasswordField;
        
        [OptionalField()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [DataMember(EmitDefaultValue=false)]
        public string CustomData {
            get {
                return this.CustomDataField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomDataField, value) != true)) {
                    this.CustomDataField = value;
                    this.RaisePropertyChanged("CustomData");
                }
            }
        }
        
        [DataMember(EmitDefaultValue=false)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [DataMember(EmitDefaultValue=false)]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Name="Visual Sitecore ServiceSoap", Namespace="http://sitecore.net/visual/", ConfigurationName="SitecoreWebservices.VisualSitecoreServiceSoap")]
    public interface VisualSitecoreServiceSoap {
        
        // CODEGEN: Generating message contract since element name id from namespace http://sitecore.net/visual/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://sitecore.net/visual/AddFromMaster", ReplyAction="*")]
        AddFromMasterResponse AddFromMaster(AddFromMasterRequest request);
        
        // CODEGEN: Generating message contract since element name id from namespace http://sitecore.net/visual/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://sitecore.net/visual/AddFromTemplate", ReplyAction="*")]
        AddFromTemplateResponse AddFromTemplate(AddFromTemplateRequest request);
        
        // CODEGEN: Generating message contract since element name id from namespace http://sitecore.net/visual/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://sitecore.net/visual/AddVersion", ReplyAction="*")]
        AddVersionResponse AddVersion(AddVersionRequest request);
        
        // CODEGEN: Generating message contract since element name id from namespace http://sitecore.net/visual/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://sitecore.net/visual/CopyTo", ReplyAction="*")]
        CopyToResponse CopyTo(CopyToRequest request);
        
        // CODEGEN: Generating message contract since element name id from namespace http://sitecore.net/visual/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://sitecore.net/visual/Delete", ReplyAction="*")]
        DeleteResponse Delete(DeleteRequest request);
        
        // CODEGEN: Generating message contract since element name id from namespace http://sitecore.net/visual/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://sitecore.net/visual/DeleteChildren", ReplyAction="*")]
        DeleteChildrenResponse DeleteChildren(DeleteChildrenRequest request);
        
        // CODEGEN: Generating message contract since element name id from namespace http://sitecore.net/visual/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://sitecore.net/visual/Duplicate", ReplyAction="*")]
        DuplicateResponse Duplicate(DuplicateRequest request);
        
        // CODEGEN: Generating message contract since element name id from namespace http://sitecore.net/visual/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://sitecore.net/visual/GetChildren", ReplyAction="*")]
        GetChildrenResponse GetChildren(GetChildrenRequest request);
        
        // CODEGEN: Generating message contract since element name credentials from namespace http://sitecore.net/visual/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://sitecore.net/visual/GetDatabases", ReplyAction="*")]
        GetDatabasesResponse GetDatabases(GetDatabasesRequest request);
        
        // CODEGEN: Generating message contract since element name id from namespace http://sitecore.net/visual/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://sitecore.net/visual/GetItemMasters", ReplyAction="*")]
        GetItemMastersResponse GetItemMasters(GetItemMastersRequest request);
        
        // CODEGEN: Generating message contract since element name id from namespace http://sitecore.net/visual/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://sitecore.net/visual/GetItemFields", ReplyAction="*")]
        GetItemFieldsResponse GetItemFields(GetItemFieldsRequest request);
        
        // CODEGEN: Generating message contract since element name databaseName from namespace http://sitecore.net/visual/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://sitecore.net/visual/GetLanguages", ReplyAction="*")]
        GetLanguagesResponse GetLanguages(GetLanguagesRequest request);
        
        // CODEGEN: Generating message contract since element name databaseName from namespace http://sitecore.net/visual/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://sitecore.net/visual/GetMasters", ReplyAction="*")]
        GetMastersResponse GetMasters(GetMastersRequest request);
        
        // CODEGEN: Generating message contract since element name databaseName from namespace http://sitecore.net/visual/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://sitecore.net/visual/GetTemplates", ReplyAction="*")]
        GetTemplatesResponse GetTemplates(GetTemplatesRequest request);
        
        // CODEGEN: Generating message contract since element name id from namespace http://sitecore.net/visual/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://sitecore.net/visual/GetXML", ReplyAction="*")]
        GetXMLResponse GetXML(GetXMLRequest request);
        
        // CODEGEN: Generating message contract since element name id from namespace http://sitecore.net/visual/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://sitecore.net/visual/InsertXML", ReplyAction="*")]
        InsertXMLResponse InsertXML(InsertXMLRequest request);
        
        // CODEGEN: Generating message contract since element name id from namespace http://sitecore.net/visual/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://sitecore.net/visual/MoveTo", ReplyAction="*")]
        MoveToResponse MoveTo(MoveToRequest request);
        
        // CODEGEN: Generating message contract since element name id from namespace http://sitecore.net/visual/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://sitecore.net/visual/RemoveVersion", ReplyAction="*")]
        RemoveVersionResponse RemoveVersion(RemoveVersionRequest request);
        
        // CODEGEN: Generating message contract since element name id from namespace http://sitecore.net/visual/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://sitecore.net/visual/Rename", ReplyAction="*")]
        RenameResponse Rename(RenameRequest request);
        
        // CODEGEN: Generating message contract since element name xml from namespace http://sitecore.net/visual/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://sitecore.net/visual/Save", ReplyAction="*")]
        SaveResponse Save(SaveRequest request);
        
        // CODEGEN: Generating message contract since element name credentials from namespace http://sitecore.net/visual/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://sitecore.net/visual/VerifyCredentials", ReplyAction="*")]
        VerifyCredentialsResponse VerifyCredentials(VerifyCredentialsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddFromMasterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddFromMaster", Namespace="http://sitecore.net/visual/", Order=0)]
        public AddFromMasterRequestBody Body;
        
        public AddFromMasterRequest() {
        }
        
        public AddFromMasterRequest(AddFromMasterRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="http://sitecore.net/visual/")]
    public partial class AddFromMasterRequestBody {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public string id;
        
        [DataMember(EmitDefaultValue=false, Order=1)]
        public string masterID;
        
        [DataMember(EmitDefaultValue=false, Order=2)]
        public string name;
        
        [DataMember(EmitDefaultValue=false, Order=3)]
        public string databaseName;
        
        [DataMember(EmitDefaultValue=false, Order=4)]
        public Credentials credentials;
        
        public AddFromMasterRequestBody() {
        }
        
        public AddFromMasterRequestBody(string id, string masterID, string name, string databaseName, Credentials credentials) {
            this.id = id;
            this.masterID = masterID;
            this.name = name;
            this.databaseName = databaseName;
            this.credentials = credentials;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddFromMasterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddFromMasterResponse", Namespace="http://sitecore.net/visual/", Order=0)]
        public AddFromMasterResponseBody Body;
        
        public AddFromMasterResponse() {
        }
        
        public AddFromMasterResponse(AddFromMasterResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="http://sitecore.net/visual/")]
    public partial class AddFromMasterResponseBody {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement AddFromMasterResult;
        
        public AddFromMasterResponseBody() {
        }
        
        public AddFromMasterResponseBody(System.Xml.Linq.XElement AddFromMasterResult) {
            this.AddFromMasterResult = AddFromMasterResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddFromTemplateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddFromTemplate", Namespace="http://sitecore.net/visual/", Order=0)]
        public AddFromTemplateRequestBody Body;
        
        public AddFromTemplateRequest() {
        }
        
        public AddFromTemplateRequest(AddFromTemplateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="http://sitecore.net/visual/")]
    public partial class AddFromTemplateRequestBody {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public string id;
        
        [DataMember(EmitDefaultValue=false, Order=1)]
        public string templateID;
        
        [DataMember(EmitDefaultValue=false, Order=2)]
        public string name;
        
        [DataMember(EmitDefaultValue=false, Order=3)]
        public string databaseName;
        
        [DataMember(EmitDefaultValue=false, Order=4)]
        public Credentials credentials;
        
        public AddFromTemplateRequestBody() {
        }
        
        public AddFromTemplateRequestBody(string id, string templateID, string name, string databaseName, Credentials credentials) {
            this.id = id;
            this.templateID = templateID;
            this.name = name;
            this.databaseName = databaseName;
            this.credentials = credentials;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddFromTemplateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddFromTemplateResponse", Namespace="http://sitecore.net/visual/", Order=0)]
        public AddFromTemplateResponseBody Body;
        
        public AddFromTemplateResponse() {
        }
        
        public AddFromTemplateResponse(AddFromTemplateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="http://sitecore.net/visual/")]
    public partial class AddFromTemplateResponseBody {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement AddFromTemplateResult;
        
        public AddFromTemplateResponseBody() {
        }
        
        public AddFromTemplateResponseBody(System.Xml.Linq.XElement AddFromTemplateResult) {
            this.AddFromTemplateResult = AddFromTemplateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddVersionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddVersion", Namespace="http://sitecore.net/visual/", Order=0)]
        public AddVersionRequestBody Body;
        
        public AddVersionRequest() {
        }
        
        public AddVersionRequest(AddVersionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="http://sitecore.net/visual/")]
    public partial class AddVersionRequestBody {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public string id;
        
        [DataMember(EmitDefaultValue=false, Order=1)]
        public string language;
        
        [DataMember(EmitDefaultValue=false, Order=2)]
        public string databaseName;
        
        [DataMember(EmitDefaultValue=false, Order=3)]
        public Credentials credentials;
        
        public AddVersionRequestBody() {
        }
        
        public AddVersionRequestBody(string id, string language, string databaseName, Credentials credentials) {
            this.id = id;
            this.language = language;
            this.databaseName = databaseName;
            this.credentials = credentials;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddVersionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddVersionResponse", Namespace="http://sitecore.net/visual/", Order=0)]
        public AddVersionResponseBody Body;
        
        public AddVersionResponse() {
        }
        
        public AddVersionResponse(AddVersionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="http://sitecore.net/visual/")]
    public partial class AddVersionResponseBody {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement AddVersionResult;
        
        public AddVersionResponseBody() {
        }
        
        public AddVersionResponseBody(System.Xml.Linq.XElement AddVersionResult) {
            this.AddVersionResult = AddVersionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CopyToRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CopyTo", Namespace="http://sitecore.net/visual/", Order=0)]
        public CopyToRequestBody Body;
        
        public CopyToRequest() {
        }
        
        public CopyToRequest(CopyToRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="http://sitecore.net/visual/")]
    public partial class CopyToRequestBody {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public string id;
        
        [DataMember(EmitDefaultValue=false, Order=1)]
        public string newParent;
        
        [DataMember(EmitDefaultValue=false, Order=2)]
        public string name;
        
        [DataMember(EmitDefaultValue=false, Order=3)]
        public string databaseName;
        
        [DataMember(EmitDefaultValue=false, Order=4)]
        public Credentials credentials;
        
        public CopyToRequestBody() {
        }
        
        public CopyToRequestBody(string id, string newParent, string name, string databaseName, Credentials credentials) {
            this.id = id;
            this.newParent = newParent;
            this.name = name;
            this.databaseName = databaseName;
            this.credentials = credentials;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CopyToResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CopyToResponse", Namespace="http://sitecore.net/visual/", Order=0)]
        public CopyToResponseBody Body;
        
        public CopyToResponse() {
        }
        
        public CopyToResponse(CopyToResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="http://sitecore.net/visual/")]
    public partial class CopyToResponseBody {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement CopyToResult;
        
        public CopyToResponseBody() {
        }
        
        public CopyToResponseBody(System.Xml.Linq.XElement CopyToResult) {
            this.CopyToResult = CopyToResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete", Namespace="http://sitecore.net/visual/", Order=0)]
        public DeleteRequestBody Body;
        
        public DeleteRequest() {
        }
        
        public DeleteRequest(DeleteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="http://sitecore.net/visual/")]
    public partial class DeleteRequestBody {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public string id;
        
        [DataMember(Order=1)]
        public bool recycle;
        
        [DataMember(EmitDefaultValue=false, Order=2)]
        public string databaseName;
        
        [DataMember(EmitDefaultValue=false, Order=3)]
        public Credentials credentials;
        
        public DeleteRequestBody() {
        }
        
        public DeleteRequestBody(string id, bool recycle, string databaseName, Credentials credentials) {
            this.id = id;
            this.recycle = recycle;
            this.databaseName = databaseName;
            this.credentials = credentials;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteResponse", Namespace="http://sitecore.net/visual/", Order=0)]
        public DeleteResponseBody Body;
        
        public DeleteResponse() {
        }
        
        public DeleteResponse(DeleteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="http://sitecore.net/visual/")]
    public partial class DeleteResponseBody {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement DeleteResult;
        
        public DeleteResponseBody() {
        }
        
        public DeleteResponseBody(System.Xml.Linq.XElement DeleteResult) {
            this.DeleteResult = DeleteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteChildrenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteChildren", Namespace="http://sitecore.net/visual/", Order=0)]
        public DeleteChildrenRequestBody Body;
        
        public DeleteChildrenRequest() {
        }
        
        public DeleteChildrenRequest(DeleteChildrenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="http://sitecore.net/visual/")]
    public partial class DeleteChildrenRequestBody {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public string id;
        
        [DataMember(EmitDefaultValue=false, Order=1)]
        public string databaseName;
        
        [DataMember(EmitDefaultValue=false, Order=2)]
        public Credentials credentials;
        
        public DeleteChildrenRequestBody() {
        }
        
        public DeleteChildrenRequestBody(string id, string databaseName, Credentials credentials) {
            this.id = id;
            this.databaseName = databaseName;
            this.credentials = credentials;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteChildrenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteChildrenResponse", Namespace="http://sitecore.net/visual/", Order=0)]
        public DeleteChildrenResponseBody Body;
        
        public DeleteChildrenResponse() {
        }
        
        public DeleteChildrenResponse(DeleteChildrenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="http://sitecore.net/visual/")]
    public partial class DeleteChildrenResponseBody {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement DeleteChildrenResult;
        
        public DeleteChildrenResponseBody() {
        }
        
        public DeleteChildrenResponseBody(System.Xml.Linq.XElement DeleteChildrenResult) {
            this.DeleteChildrenResult = DeleteChildrenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DuplicateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Duplicate", Namespace="http://sitecore.net/visual/", Order=0)]
        public DuplicateRequestBody Body;
        
        public DuplicateRequest() {
        }
        
        public DuplicateRequest(DuplicateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="http://sitecore.net/visual/")]
    public partial class DuplicateRequestBody {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public string id;
        
        [DataMember(EmitDefaultValue=false, Order=1)]
        public string name;
        
        [DataMember(EmitDefaultValue=false, Order=2)]
        public string databaseName;
        
        [DataMember(EmitDefaultValue=false, Order=3)]
        public Credentials credentials;
        
        public DuplicateRequestBody() {
        }
        
        public DuplicateRequestBody(string id, string name, string databaseName, Credentials credentials) {
            this.id = id;
            this.name = name;
            this.databaseName = databaseName;
            this.credentials = credentials;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DuplicateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DuplicateResponse", Namespace="http://sitecore.net/visual/", Order=0)]
        public DuplicateResponseBody Body;
        
        public DuplicateResponse() {
        }
        
        public DuplicateResponse(DuplicateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="http://sitecore.net/visual/")]
    public partial class DuplicateResponseBody {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement DuplicateResult;
        
        public DuplicateResponseBody() {
        }
        
        public DuplicateResponseBody(System.Xml.Linq.XElement DuplicateResult) {
            this.DuplicateResult = DuplicateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetChildrenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetChildren", Namespace="http://sitecore.net/visual/", Order=0)]
        public GetChildrenRequestBody Body;
        
        public GetChildrenRequest() {
        }
        
        public GetChildrenRequest(GetChildrenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="http://sitecore.net/visual/")]
    public partial class GetChildrenRequestBody {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public string id;
        
        [DataMember(EmitDefaultValue=false, Order=1)]
        public string databaseName;
        
        [DataMember(EmitDefaultValue=false, Order=2)]
        public Credentials credentials;
        
        public GetChildrenRequestBody() {
        }
        
        public GetChildrenRequestBody(string id, string databaseName, Credentials credentials) {
            this.id = id;
            this.databaseName = databaseName;
            this.credentials = credentials;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetChildrenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetChildrenResponse", Namespace="http://sitecore.net/visual/", Order=0)]
        public GetChildrenResponseBody Body;
        
        public GetChildrenResponse() {
        }
        
        public GetChildrenResponse(GetChildrenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="http://sitecore.net/visual/")]
    public partial class GetChildrenResponseBody {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetChildrenResult;
        
        public GetChildrenResponseBody() {
        }
        
        public GetChildrenResponseBody(System.Xml.Linq.XElement GetChildrenResult) {
            this.GetChildrenResult = GetChildrenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDatabasesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDatabases", Namespace="http://sitecore.net/visual/", Order=0)]
        public GetDatabasesRequestBody Body;
        
        public GetDatabasesRequest() {
        }
        
        public GetDatabasesRequest(GetDatabasesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="http://sitecore.net/visual/")]
    public partial class GetDatabasesRequestBody {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public Credentials credentials;
        
        public GetDatabasesRequestBody() {
        }
        
        public GetDatabasesRequestBody(Credentials credentials) {
            this.credentials = credentials;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDatabasesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDatabasesResponse", Namespace="http://sitecore.net/visual/", Order=0)]
        public GetDatabasesResponseBody Body;
        
        public GetDatabasesResponse() {
        }
        
        public GetDatabasesResponse(GetDatabasesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="http://sitecore.net/visual/")]
    public partial class GetDatabasesResponseBody {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetDatabasesResult;
        
        public GetDatabasesResponseBody() {
        }
        
        public GetDatabasesResponseBody(System.Xml.Linq.XElement GetDatabasesResult) {
            this.GetDatabasesResult = GetDatabasesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetItemMastersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetItemMasters", Namespace="http://sitecore.net/visual/", Order=0)]
        public GetItemMastersRequestBody Body;
        
        public GetItemMastersRequest() {
        }
        
        public GetItemMastersRequest(GetItemMastersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="http://sitecore.net/visual/")]
    public partial class GetItemMastersRequestBody {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public string id;
        
        [DataMember(EmitDefaultValue=false, Order=1)]
        public string databaseName;
        
        [DataMember(EmitDefaultValue=false, Order=2)]
        public Credentials credentials;
        
        public GetItemMastersRequestBody() {
        }
        
        public GetItemMastersRequestBody(string id, string databaseName, Credentials credentials) {
            this.id = id;
            this.databaseName = databaseName;
            this.credentials = credentials;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetItemMastersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetItemMastersResponse", Namespace="http://sitecore.net/visual/", Order=0)]
        public GetItemMastersResponseBody Body;
        
        public GetItemMastersResponse() {
        }
        
        public GetItemMastersResponse(GetItemMastersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="http://sitecore.net/visual/")]
    public partial class GetItemMastersResponseBody {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetItemMastersResult;
        
        public GetItemMastersResponseBody() {
        }
        
        public GetItemMastersResponseBody(System.Xml.Linq.XElement GetItemMastersResult) {
            this.GetItemMastersResult = GetItemMastersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetItemFieldsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetItemFields", Namespace="http://sitecore.net/visual/", Order=0)]
        public GetItemFieldsRequestBody Body;
        
        public GetItemFieldsRequest() {
        }
        
        public GetItemFieldsRequest(GetItemFieldsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="http://sitecore.net/visual/")]
    public partial class GetItemFieldsRequestBody {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public string id;
        
        [DataMember(EmitDefaultValue=false, Order=1)]
        public string language;
        
        [DataMember(EmitDefaultValue=false, Order=2)]
        public string version;
        
        [DataMember(Order=3)]
        public bool allFields;
        
        [DataMember(EmitDefaultValue=false, Order=4)]
        public string databaseName;
        
        [DataMember(EmitDefaultValue=false, Order=5)]
        public Credentials credentials;
        
        public GetItemFieldsRequestBody() {
        }
        
        public GetItemFieldsRequestBody(string id, string language, string version, bool allFields, string databaseName, Credentials credentials) {
            this.id = id;
            this.language = language;
            this.version = version;
            this.allFields = allFields;
            this.databaseName = databaseName;
            this.credentials = credentials;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetItemFieldsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetItemFieldsResponse", Namespace="http://sitecore.net/visual/", Order=0)]
        public GetItemFieldsResponseBody Body;
        
        public GetItemFieldsResponse() {
        }
        
        public GetItemFieldsResponse(GetItemFieldsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="http://sitecore.net/visual/")]
    public partial class GetItemFieldsResponseBody {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetItemFieldsResult;
        
        public GetItemFieldsResponseBody() {
        }
        
        public GetItemFieldsResponseBody(System.Xml.Linq.XElement GetItemFieldsResult) {
            this.GetItemFieldsResult = GetItemFieldsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLanguagesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLanguages", Namespace="http://sitecore.net/visual/", Order=0)]
        public GetLanguagesRequestBody Body;
        
        public GetLanguagesRequest() {
        }
        
        public GetLanguagesRequest(GetLanguagesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="http://sitecore.net/visual/")]
    public partial class GetLanguagesRequestBody {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public string databaseName;
        
        [DataMember(EmitDefaultValue=false, Order=1)]
        public Credentials credentials;
        
        public GetLanguagesRequestBody() {
        }
        
        public GetLanguagesRequestBody(string databaseName, Credentials credentials) {
            this.databaseName = databaseName;
            this.credentials = credentials;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLanguagesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLanguagesResponse", Namespace="http://sitecore.net/visual/", Order=0)]
        public GetLanguagesResponseBody Body;
        
        public GetLanguagesResponse() {
        }
        
        public GetLanguagesResponse(GetLanguagesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="http://sitecore.net/visual/")]
    public partial class GetLanguagesResponseBody {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetLanguagesResult;
        
        public GetLanguagesResponseBody() {
        }
        
        public GetLanguagesResponseBody(System.Xml.Linq.XElement GetLanguagesResult) {
            this.GetLanguagesResult = GetLanguagesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMastersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMasters", Namespace="http://sitecore.net/visual/", Order=0)]
        public GetMastersRequestBody Body;
        
        public GetMastersRequest() {
        }
        
        public GetMastersRequest(GetMastersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="http://sitecore.net/visual/")]
    public partial class GetMastersRequestBody {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public string databaseName;
        
        [DataMember(EmitDefaultValue=false, Order=1)]
        public Credentials credentials;
        
        public GetMastersRequestBody() {
        }
        
        public GetMastersRequestBody(string databaseName, Credentials credentials) {
            this.databaseName = databaseName;
            this.credentials = credentials;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMastersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMastersResponse", Namespace="http://sitecore.net/visual/", Order=0)]
        public GetMastersResponseBody Body;
        
        public GetMastersResponse() {
        }
        
        public GetMastersResponse(GetMastersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="http://sitecore.net/visual/")]
    public partial class GetMastersResponseBody {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetMastersResult;
        
        public GetMastersResponseBody() {
        }
        
        public GetMastersResponseBody(System.Xml.Linq.XElement GetMastersResult) {
            this.GetMastersResult = GetMastersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTemplatesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTemplates", Namespace="http://sitecore.net/visual/", Order=0)]
        public GetTemplatesRequestBody Body;
        
        public GetTemplatesRequest() {
        }
        
        public GetTemplatesRequest(GetTemplatesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="http://sitecore.net/visual/")]
    public partial class GetTemplatesRequestBody {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public string databaseName;
        
        [DataMember(EmitDefaultValue=false, Order=1)]
        public Credentials credentials;
        
        public GetTemplatesRequestBody() {
        }
        
        public GetTemplatesRequestBody(string databaseName, Credentials credentials) {
            this.databaseName = databaseName;
            this.credentials = credentials;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTemplatesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTemplatesResponse", Namespace="http://sitecore.net/visual/", Order=0)]
        public GetTemplatesResponseBody Body;
        
        public GetTemplatesResponse() {
        }
        
        public GetTemplatesResponse(GetTemplatesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="http://sitecore.net/visual/")]
    public partial class GetTemplatesResponseBody {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetTemplatesResult;
        
        public GetTemplatesResponseBody() {
        }
        
        public GetTemplatesResponseBody(System.Xml.Linq.XElement GetTemplatesResult) {
            this.GetTemplatesResult = GetTemplatesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetXMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetXML", Namespace="http://sitecore.net/visual/", Order=0)]
        public GetXMLRequestBody Body;
        
        public GetXMLRequest() {
        }
        
        public GetXMLRequest(GetXMLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="http://sitecore.net/visual/")]
    public partial class GetXMLRequestBody {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public string id;
        
        [DataMember(Order=1)]
        public bool deep;
        
        [DataMember(EmitDefaultValue=false, Order=2)]
        public string databaseName;
        
        [DataMember(EmitDefaultValue=false, Order=3)]
        public Credentials credentials;
        
        public GetXMLRequestBody() {
        }
        
        public GetXMLRequestBody(string id, bool deep, string databaseName, Credentials credentials) {
            this.id = id;
            this.deep = deep;
            this.databaseName = databaseName;
            this.credentials = credentials;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetXMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetXMLResponse", Namespace="http://sitecore.net/visual/", Order=0)]
        public GetXMLResponseBody Body;
        
        public GetXMLResponse() {
        }
        
        public GetXMLResponse(GetXMLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="http://sitecore.net/visual/")]
    public partial class GetXMLResponseBody {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetXMLResult;
        
        public GetXMLResponseBody() {
        }
        
        public GetXMLResponseBody(System.Xml.Linq.XElement GetXMLResult) {
            this.GetXMLResult = GetXMLResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertXMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertXML", Namespace="http://sitecore.net/visual/", Order=0)]
        public InsertXMLRequestBody Body;
        
        public InsertXMLRequest() {
        }
        
        public InsertXMLRequest(InsertXMLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="http://sitecore.net/visual/")]
    public partial class InsertXMLRequestBody {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public string id;
        
        [DataMember(EmitDefaultValue=false, Order=1)]
        public string xml;
        
        [DataMember(Order=2)]
        public bool changeIDs;
        
        [DataMember(EmitDefaultValue=false, Order=3)]
        public string databaseName;
        
        [DataMember(EmitDefaultValue=false, Order=4)]
        public Credentials credentials;
        
        public InsertXMLRequestBody() {
        }
        
        public InsertXMLRequestBody(string id, string xml, bool changeIDs, string databaseName, Credentials credentials) {
            this.id = id;
            this.xml = xml;
            this.changeIDs = changeIDs;
            this.databaseName = databaseName;
            this.credentials = credentials;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertXMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertXMLResponse", Namespace="http://sitecore.net/visual/", Order=0)]
        public InsertXMLResponseBody Body;
        
        public InsertXMLResponse() {
        }
        
        public InsertXMLResponse(InsertXMLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="http://sitecore.net/visual/")]
    public partial class InsertXMLResponseBody {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement InsertXMLResult;
        
        public InsertXMLResponseBody() {
        }
        
        public InsertXMLResponseBody(System.Xml.Linq.XElement InsertXMLResult) {
            this.InsertXMLResult = InsertXMLResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MoveToRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MoveTo", Namespace="http://sitecore.net/visual/", Order=0)]
        public MoveToRequestBody Body;
        
        public MoveToRequest() {
        }
        
        public MoveToRequest(MoveToRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="http://sitecore.net/visual/")]
    public partial class MoveToRequestBody {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public string id;
        
        [DataMember(EmitDefaultValue=false, Order=1)]
        public string newParent;
        
        [DataMember(EmitDefaultValue=false, Order=2)]
        public string databaseName;
        
        [DataMember(EmitDefaultValue=false, Order=3)]
        public Credentials credentials;
        
        public MoveToRequestBody() {
        }
        
        public MoveToRequestBody(string id, string newParent, string databaseName, Credentials credentials) {
            this.id = id;
            this.newParent = newParent;
            this.databaseName = databaseName;
            this.credentials = credentials;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MoveToResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MoveToResponse", Namespace="http://sitecore.net/visual/", Order=0)]
        public MoveToResponseBody Body;
        
        public MoveToResponse() {
        }
        
        public MoveToResponse(MoveToResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="http://sitecore.net/visual/")]
    public partial class MoveToResponseBody {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement MoveToResult;
        
        public MoveToResponseBody() {
        }
        
        public MoveToResponseBody(System.Xml.Linq.XElement MoveToResult) {
            this.MoveToResult = MoveToResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveVersionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemoveVersion", Namespace="http://sitecore.net/visual/", Order=0)]
        public RemoveVersionRequestBody Body;
        
        public RemoveVersionRequest() {
        }
        
        public RemoveVersionRequest(RemoveVersionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="http://sitecore.net/visual/")]
    public partial class RemoveVersionRequestBody {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public string id;
        
        [DataMember(EmitDefaultValue=false, Order=1)]
        public string language;
        
        [DataMember(EmitDefaultValue=false, Order=2)]
        public string version;
        
        [DataMember(EmitDefaultValue=false, Order=3)]
        public string databaseName;
        
        [DataMember(EmitDefaultValue=false, Order=4)]
        public Credentials credentials;
        
        public RemoveVersionRequestBody() {
        }
        
        public RemoveVersionRequestBody(string id, string language, string version, string databaseName, Credentials credentials) {
            this.id = id;
            this.language = language;
            this.version = version;
            this.databaseName = databaseName;
            this.credentials = credentials;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveVersionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemoveVersionResponse", Namespace="http://sitecore.net/visual/", Order=0)]
        public RemoveVersionResponseBody Body;
        
        public RemoveVersionResponse() {
        }
        
        public RemoveVersionResponse(RemoveVersionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="http://sitecore.net/visual/")]
    public partial class RemoveVersionResponseBody {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement RemoveVersionResult;
        
        public RemoveVersionResponseBody() {
        }
        
        public RemoveVersionResponseBody(System.Xml.Linq.XElement RemoveVersionResult) {
            this.RemoveVersionResult = RemoveVersionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RenameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Rename", Namespace="http://sitecore.net/visual/", Order=0)]
        public RenameRequestBody Body;
        
        public RenameRequest() {
        }
        
        public RenameRequest(RenameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="http://sitecore.net/visual/")]
    public partial class RenameRequestBody {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public string id;
        
        [DataMember(EmitDefaultValue=false, Order=1)]
        public string newName;
        
        [DataMember(EmitDefaultValue=false, Order=2)]
        public string databaseName;
        
        [DataMember(EmitDefaultValue=false, Order=3)]
        public Credentials credentials;
        
        public RenameRequestBody() {
        }
        
        public RenameRequestBody(string id, string newName, string databaseName, Credentials credentials) {
            this.id = id;
            this.newName = newName;
            this.databaseName = databaseName;
            this.credentials = credentials;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RenameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RenameResponse", Namespace="http://sitecore.net/visual/", Order=0)]
        public RenameResponseBody Body;
        
        public RenameResponse() {
        }
        
        public RenameResponse(RenameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="http://sitecore.net/visual/")]
    public partial class RenameResponseBody {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement RenameResult;
        
        public RenameResponseBody() {
        }
        
        public RenameResponseBody(System.Xml.Linq.XElement RenameResult) {
            this.RenameResult = RenameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Save", Namespace="http://sitecore.net/visual/", Order=0)]
        public SaveRequestBody Body;
        
        public SaveRequest() {
        }
        
        public SaveRequest(SaveRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="http://sitecore.net/visual/")]
    public partial class SaveRequestBody {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public string xml;
        
        [DataMember(EmitDefaultValue=false, Order=1)]
        public string databaseName;
        
        [DataMember(EmitDefaultValue=false, Order=2)]
        public Credentials credentials;
        
        public SaveRequestBody() {
        }
        
        public SaveRequestBody(string xml, string databaseName, Credentials credentials) {
            this.xml = xml;
            this.databaseName = databaseName;
            this.credentials = credentials;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveResponse", Namespace="http://sitecore.net/visual/", Order=0)]
        public SaveResponseBody Body;
        
        public SaveResponse() {
        }
        
        public SaveResponse(SaveResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="http://sitecore.net/visual/")]
    public partial class SaveResponseBody {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement SaveResult;
        
        public SaveResponseBody() {
        }
        
        public SaveResponseBody(System.Xml.Linq.XElement SaveResult) {
            this.SaveResult = SaveResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerifyCredentialsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerifyCredentials", Namespace="http://sitecore.net/visual/", Order=0)]
        public VerifyCredentialsRequestBody Body;
        
        public VerifyCredentialsRequest() {
        }
        
        public VerifyCredentialsRequest(VerifyCredentialsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="http://sitecore.net/visual/")]
    public partial class VerifyCredentialsRequestBody {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public Credentials credentials;
        
        public VerifyCredentialsRequestBody() {
        }
        
        public VerifyCredentialsRequestBody(Credentials credentials) {
            this.credentials = credentials;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerifyCredentialsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerifyCredentialsResponse", Namespace="http://sitecore.net/visual/", Order=0)]
        public VerifyCredentialsResponseBody Body;
        
        public VerifyCredentialsResponse() {
        }
        
        public VerifyCredentialsResponse(VerifyCredentialsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="http://sitecore.net/visual/")]
    public partial class VerifyCredentialsResponseBody {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement VerifyCredentialsResult;
        
        public VerifyCredentialsResponseBody() {
        }
        
        public VerifyCredentialsResponseBody(System.Xml.Linq.XElement VerifyCredentialsResult) {
            this.VerifyCredentialsResult = VerifyCredentialsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface VisualSitecoreServiceSoapChannel : VisualSitecoreServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VisualSitecoreServiceSoapClient : System.ServiceModel.ClientBase<VisualSitecoreServiceSoap>, VisualSitecoreServiceSoap {
        
        public VisualSitecoreServiceSoapClient() {
        }
        
        public VisualSitecoreServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VisualSitecoreServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VisualSitecoreServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VisualSitecoreServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AddFromMasterResponse VisualSitecoreServiceSoap.AddFromMaster(AddFromMasterRequest request) {
            return base.Channel.AddFromMaster(request);
        }
        
        public System.Xml.Linq.XElement AddFromMaster(string id, string masterID, string name, string databaseName, Credentials credentials) {
            AddFromMasterRequest inValue = new AddFromMasterRequest();
            inValue.Body = new AddFromMasterRequestBody();
            inValue.Body.id = id;
            inValue.Body.masterID = masterID;
            inValue.Body.name = name;
            inValue.Body.databaseName = databaseName;
            inValue.Body.credentials = credentials;
            AddFromMasterResponse retVal = ((VisualSitecoreServiceSoap)(this)).AddFromMaster(inValue);
            return retVal.Body.AddFromMasterResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AddFromTemplateResponse VisualSitecoreServiceSoap.AddFromTemplate(AddFromTemplateRequest request) {
            return base.Channel.AddFromTemplate(request);
        }
        
        public System.Xml.Linq.XElement AddFromTemplate(string id, string templateID, string name, string databaseName, Credentials credentials) {
            AddFromTemplateRequest inValue = new AddFromTemplateRequest();
            inValue.Body = new AddFromTemplateRequestBody();
            inValue.Body.id = id;
            inValue.Body.templateID = templateID;
            inValue.Body.name = name;
            inValue.Body.databaseName = databaseName;
            inValue.Body.credentials = credentials;
            AddFromTemplateResponse retVal = ((VisualSitecoreServiceSoap)(this)).AddFromTemplate(inValue);
            return retVal.Body.AddFromTemplateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AddVersionResponse VisualSitecoreServiceSoap.AddVersion(AddVersionRequest request) {
            return base.Channel.AddVersion(request);
        }
        
        public System.Xml.Linq.XElement AddVersion(string id, string language, string databaseName, Credentials credentials) {
            AddVersionRequest inValue = new AddVersionRequest();
            inValue.Body = new AddVersionRequestBody();
            inValue.Body.id = id;
            inValue.Body.language = language;
            inValue.Body.databaseName = databaseName;
            inValue.Body.credentials = credentials;
            AddVersionResponse retVal = ((VisualSitecoreServiceSoap)(this)).AddVersion(inValue);
            return retVal.Body.AddVersionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CopyToResponse VisualSitecoreServiceSoap.CopyTo(CopyToRequest request) {
            return base.Channel.CopyTo(request);
        }
        
        public System.Xml.Linq.XElement CopyTo(string id, string newParent, string name, string databaseName, Credentials credentials) {
            CopyToRequest inValue = new CopyToRequest();
            inValue.Body = new CopyToRequestBody();
            inValue.Body.id = id;
            inValue.Body.newParent = newParent;
            inValue.Body.name = name;
            inValue.Body.databaseName = databaseName;
            inValue.Body.credentials = credentials;
            CopyToResponse retVal = ((VisualSitecoreServiceSoap)(this)).CopyTo(inValue);
            return retVal.Body.CopyToResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DeleteResponse VisualSitecoreServiceSoap.Delete(DeleteRequest request) {
            return base.Channel.Delete(request);
        }
        
        public System.Xml.Linq.XElement Delete(string id, bool recycle, string databaseName, Credentials credentials) {
            DeleteRequest inValue = new DeleteRequest();
            inValue.Body = new DeleteRequestBody();
            inValue.Body.id = id;
            inValue.Body.recycle = recycle;
            inValue.Body.databaseName = databaseName;
            inValue.Body.credentials = credentials;
            DeleteResponse retVal = ((VisualSitecoreServiceSoap)(this)).Delete(inValue);
            return retVal.Body.DeleteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DeleteChildrenResponse VisualSitecoreServiceSoap.DeleteChildren(DeleteChildrenRequest request) {
            return base.Channel.DeleteChildren(request);
        }
        
        public System.Xml.Linq.XElement DeleteChildren(string id, string databaseName, Credentials credentials) {
            DeleteChildrenRequest inValue = new DeleteChildrenRequest();
            inValue.Body = new DeleteChildrenRequestBody();
            inValue.Body.id = id;
            inValue.Body.databaseName = databaseName;
            inValue.Body.credentials = credentials;
            DeleteChildrenResponse retVal = ((VisualSitecoreServiceSoap)(this)).DeleteChildren(inValue);
            return retVal.Body.DeleteChildrenResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DuplicateResponse VisualSitecoreServiceSoap.Duplicate(DuplicateRequest request) {
            return base.Channel.Duplicate(request);
        }
        
        public System.Xml.Linq.XElement Duplicate(string id, string name, string databaseName, Credentials credentials) {
            DuplicateRequest inValue = new DuplicateRequest();
            inValue.Body = new DuplicateRequestBody();
            inValue.Body.id = id;
            inValue.Body.name = name;
            inValue.Body.databaseName = databaseName;
            inValue.Body.credentials = credentials;
            DuplicateResponse retVal = ((VisualSitecoreServiceSoap)(this)).Duplicate(inValue);
            return retVal.Body.DuplicateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GetChildrenResponse VisualSitecoreServiceSoap.GetChildren(GetChildrenRequest request) {
            return base.Channel.GetChildren(request);
        }
        
        public System.Xml.Linq.XElement GetChildren(string id, string databaseName, Credentials credentials) {
            GetChildrenRequest inValue = new GetChildrenRequest();
            inValue.Body = new GetChildrenRequestBody();
            inValue.Body.id = id;
            inValue.Body.databaseName = databaseName;
            inValue.Body.credentials = credentials;
            GetChildrenResponse retVal = ((VisualSitecoreServiceSoap)(this)).GetChildren(inValue);
            return retVal.Body.GetChildrenResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GetDatabasesResponse VisualSitecoreServiceSoap.GetDatabases(GetDatabasesRequest request) {
            return base.Channel.GetDatabases(request);
        }
        
        public System.Xml.Linq.XElement GetDatabases(Credentials credentials) {
            GetDatabasesRequest inValue = new GetDatabasesRequest();
            inValue.Body = new GetDatabasesRequestBody();
            inValue.Body.credentials = credentials;
            GetDatabasesResponse retVal = ((VisualSitecoreServiceSoap)(this)).GetDatabases(inValue);
            return retVal.Body.GetDatabasesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GetItemMastersResponse VisualSitecoreServiceSoap.GetItemMasters(GetItemMastersRequest request) {
            return base.Channel.GetItemMasters(request);
        }
        
        public System.Xml.Linq.XElement GetItemMasters(string id, string databaseName, Credentials credentials) {
            GetItemMastersRequest inValue = new GetItemMastersRequest();
            inValue.Body = new GetItemMastersRequestBody();
            inValue.Body.id = id;
            inValue.Body.databaseName = databaseName;
            inValue.Body.credentials = credentials;
            GetItemMastersResponse retVal = ((VisualSitecoreServiceSoap)(this)).GetItemMasters(inValue);
            return retVal.Body.GetItemMastersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GetItemFieldsResponse VisualSitecoreServiceSoap.GetItemFields(GetItemFieldsRequest request) {
            return base.Channel.GetItemFields(request);
        }
        
        public System.Xml.Linq.XElement GetItemFields(string id, string language, string version, bool allFields, string databaseName, Credentials credentials) {
            GetItemFieldsRequest inValue = new GetItemFieldsRequest();
            inValue.Body = new GetItemFieldsRequestBody();
            inValue.Body.id = id;
            inValue.Body.language = language;
            inValue.Body.version = version;
            inValue.Body.allFields = allFields;
            inValue.Body.databaseName = databaseName;
            inValue.Body.credentials = credentials;
            GetItemFieldsResponse retVal = ((VisualSitecoreServiceSoap)(this)).GetItemFields(inValue);
            return retVal.Body.GetItemFieldsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GetLanguagesResponse VisualSitecoreServiceSoap.GetLanguages(GetLanguagesRequest request) {
            return base.Channel.GetLanguages(request);
        }
        
        public System.Xml.Linq.XElement GetLanguages(string databaseName, Credentials credentials) {
            GetLanguagesRequest inValue = new GetLanguagesRequest();
            inValue.Body = new GetLanguagesRequestBody();
            inValue.Body.databaseName = databaseName;
            inValue.Body.credentials = credentials;
            GetLanguagesResponse retVal = ((VisualSitecoreServiceSoap)(this)).GetLanguages(inValue);
            return retVal.Body.GetLanguagesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GetMastersResponse VisualSitecoreServiceSoap.GetMasters(GetMastersRequest request) {
            return base.Channel.GetMasters(request);
        }
        
        public System.Xml.Linq.XElement GetMasters(string databaseName, Credentials credentials) {
            GetMastersRequest inValue = new GetMastersRequest();
            inValue.Body = new GetMastersRequestBody();
            inValue.Body.databaseName = databaseName;
            inValue.Body.credentials = credentials;
            GetMastersResponse retVal = ((VisualSitecoreServiceSoap)(this)).GetMasters(inValue);
            return retVal.Body.GetMastersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GetTemplatesResponse VisualSitecoreServiceSoap.GetTemplates(GetTemplatesRequest request) {
            return base.Channel.GetTemplates(request);
        }
        
        public System.Xml.Linq.XElement GetTemplates(string databaseName, Credentials credentials) {
            GetTemplatesRequest inValue = new GetTemplatesRequest();
            inValue.Body = new GetTemplatesRequestBody();
            inValue.Body.databaseName = databaseName;
            inValue.Body.credentials = credentials;
            GetTemplatesResponse retVal = ((VisualSitecoreServiceSoap)(this)).GetTemplates(inValue);
            return retVal.Body.GetTemplatesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GetXMLResponse VisualSitecoreServiceSoap.GetXML(GetXMLRequest request) {
            return base.Channel.GetXML(request);
        }
        
        public System.Xml.Linq.XElement GetXML(string id, bool deep, string databaseName, Credentials credentials) {
            GetXMLRequest inValue = new GetXMLRequest();
            inValue.Body = new GetXMLRequestBody();
            inValue.Body.id = id;
            inValue.Body.deep = deep;
            inValue.Body.databaseName = databaseName;
            inValue.Body.credentials = credentials;
            GetXMLResponse retVal = ((VisualSitecoreServiceSoap)(this)).GetXML(inValue);
            return retVal.Body.GetXMLResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InsertXMLResponse VisualSitecoreServiceSoap.InsertXML(InsertXMLRequest request) {
            return base.Channel.InsertXML(request);
        }
        
        public System.Xml.Linq.XElement InsertXML(string id, string xml, bool changeIDs, string databaseName, Credentials credentials) {
            InsertXMLRequest inValue = new InsertXMLRequest();
            inValue.Body = new InsertXMLRequestBody();
            inValue.Body.id = id;
            inValue.Body.xml = xml;
            inValue.Body.changeIDs = changeIDs;
            inValue.Body.databaseName = databaseName;
            inValue.Body.credentials = credentials;
            InsertXMLResponse retVal = ((VisualSitecoreServiceSoap)(this)).InsertXML(inValue);
            return retVal.Body.InsertXMLResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MoveToResponse VisualSitecoreServiceSoap.MoveTo(MoveToRequest request) {
            return base.Channel.MoveTo(request);
        }
        
        public System.Xml.Linq.XElement MoveTo(string id, string newParent, string databaseName, Credentials credentials) {
            MoveToRequest inValue = new MoveToRequest();
            inValue.Body = new MoveToRequestBody();
            inValue.Body.id = id;
            inValue.Body.newParent = newParent;
            inValue.Body.databaseName = databaseName;
            inValue.Body.credentials = credentials;
            MoveToResponse retVal = ((VisualSitecoreServiceSoap)(this)).MoveTo(inValue);
            return retVal.Body.MoveToResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RemoveVersionResponse VisualSitecoreServiceSoap.RemoveVersion(RemoveVersionRequest request) {
            return base.Channel.RemoveVersion(request);
        }
        
        public System.Xml.Linq.XElement RemoveVersion(string id, string language, string version, string databaseName, Credentials credentials) {
            RemoveVersionRequest inValue = new RemoveVersionRequest();
            inValue.Body = new RemoveVersionRequestBody();
            inValue.Body.id = id;
            inValue.Body.language = language;
            inValue.Body.version = version;
            inValue.Body.databaseName = databaseName;
            inValue.Body.credentials = credentials;
            RemoveVersionResponse retVal = ((VisualSitecoreServiceSoap)(this)).RemoveVersion(inValue);
            return retVal.Body.RemoveVersionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RenameResponse VisualSitecoreServiceSoap.Rename(RenameRequest request) {
            return base.Channel.Rename(request);
        }
        
        public System.Xml.Linq.XElement Rename(string id, string newName, string databaseName, Credentials credentials) {
            RenameRequest inValue = new RenameRequest();
            inValue.Body = new RenameRequestBody();
            inValue.Body.id = id;
            inValue.Body.newName = newName;
            inValue.Body.databaseName = databaseName;
            inValue.Body.credentials = credentials;
            RenameResponse retVal = ((VisualSitecoreServiceSoap)(this)).Rename(inValue);
            return retVal.Body.RenameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SaveResponse VisualSitecoreServiceSoap.Save(SaveRequest request) {
            return base.Channel.Save(request);
        }
        
        public System.Xml.Linq.XElement Save(string xml, string databaseName, Credentials credentials) {
            SaveRequest inValue = new SaveRequest();
            inValue.Body = new SaveRequestBody();
            inValue.Body.xml = xml;
            inValue.Body.databaseName = databaseName;
            inValue.Body.credentials = credentials;
            SaveResponse retVal = ((VisualSitecoreServiceSoap)(this)).Save(inValue);
            return retVal.Body.SaveResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VerifyCredentialsResponse VisualSitecoreServiceSoap.VerifyCredentials(VerifyCredentialsRequest request) {
            return base.Channel.VerifyCredentials(request);
        }
        
        public System.Xml.Linq.XElement VerifyCredentials(Credentials credentials) {
            VerifyCredentialsRequest inValue = new VerifyCredentialsRequest();
            inValue.Body = new VerifyCredentialsRequestBody();
            inValue.Body.credentials = credentials;
            VerifyCredentialsResponse retVal = ((VisualSitecoreServiceSoap)(this)).VerifyCredentials(inValue);
            return retVal.Body.VerifyCredentialsResult;
        }
    }
}
